logging:
  level:
    org.springframework: info
server:
  port: 5000
spring:
  main:
    banner-mode: off
  application:
    name: FunBit
  datasource:
    url: jdbc:mysql://localhost:3306/databaseName
    username: jongwon
    password: 1234
  jpa:
    defer-datasource-initialization: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    ddl-auto: create
    generate-ddl: false
    show-sql: true
    properties:
      hibernate.format_sql: true

