logging:
  level:
    org.springframework: info
server:
  port: 5000
spring:
  jwt:
    secretkey: dsfkljwelkvoidflfkewhqklkdhviwelndmnvkdlhfjiepowrlkwenrdkfvkdskfnsdafdf
  security:
    user:
      name: jongwon
      password: 1234
  main:
    banner-mode: off
  application:
    name: FunBit
  datasource:
    url: jdbc:mysql://localhost:3306/${RDS_DB_NAME:social-media-database}
    username: ${RDS_USERNAME:social-media-user}
    password: ${RDS_PASSWORD:dummypassword}
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    defer-datasource-initialization: true
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
      hibernate.format_sql: true
management:
  endpoints:
    web:
      exposure:
        include: "*"